# Generated by Django 3.2.24 on 2026-09-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordreset',
            options={'managed': True},
        ),
        migrations.RemoveIndex(
            model_name='logs',
            name='logs_content_532f33_idx',
        ),
        migrations.RemoveIndex(
            model_name='personalaccesstoken',
            name='personal_acc_tokenab_2e3e7f_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='report_user_id_59a3ab_idx',
        ),
        migrations.AddIndex(
            model_name='logs',
            index=models.Index(fields=['content'], name='logs_content_db7ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='personalaccesstoken',
            index=models.Index(fields=['tokenable_type', 'tokenable_id'], name='personal_ac_tokenab_af031f_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['user_id'], name='report_user_id_b99432_idx'),
        ),
    ]
