# Generated by Django 3.2.24 on 2026-09-16 12:38

import apps.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260916_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livereport',
            name='files',
            field=apps.core.models.LegacyJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommend',
            name='file',
            field=apps.core.models.LegacyJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='dinner_reservation',
            field=apps.core.models.LegacyJSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='scanfiles',
            name='files',
            field=apps.core.models.LegacyJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
