# Generated by Django 3.2.24 on 2026-09-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20260916_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='card',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='crew',
            name='name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='draw',
            name='name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='files',
            name='filename',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='files',
            name='type',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='files',
            name='url',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='leader',
            name='card',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='leader',
            name='name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='leader',
            name='phone',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='livereport',
            name='choir_name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='livereport',
            name='contact_name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='livereport',
            name='contact_phone',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='livereport',
            name='district_or_school_name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='livereport',
            name='group',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='livereport',
            name='name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='logs',
            name='content',
            field=models.CharField(default=' ', max_length=5000),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='email',
            field=models.CharField(db_index=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='card',
            field=models.CharField(default=' ', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='personalaccesstoken',
            name='name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='personalaccesstoken',
            name='token',
            field=models.CharField(default=' ', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='choir_name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='contact_name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='contact_phone',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='establishment',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='group',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type_name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketsubscribe',
            name='card',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketsubscribe',
            name='code',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketsubscribe',
            name='ip',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketsubscribe',
            name='name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketsubscribe',
            name='phone',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=' ', max_length=30, unique=True),
        ),
    ]
