# Generated by Django 3.2.24 on 2026-09-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20260921_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDraft',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('scope', models.SmallIntegerField()),
                ('report_id', models.BigIntegerField(blank=True, null=True)),
                ('payload', models.TextField()),
                ('schema_version', models.IntegerField(default=1)),
                ('version', models.IntegerField(default=1)),
                ('state', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_draft',
            },
        ),
        migrations.AddIndex(
            model_name='reportdraft',
            index=models.Index(fields=['user_id', 'scope', 'state', 'updated_at'], name='draft_user_state_idx'),
        ),
        migrations.AddIndex(
            model_name='reportdraft',
            index=models.Index(fields=['report_id'], name='draft_report_idx'),
        ),
    ]
