# Generated by Django 3.2.24 on 2026-09-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_db_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='card',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
